# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28f0d48a24957f901839d210254024b8e35aa48d417c4fdd6651fc00b29c2d11e73b82e17b88321ab571f789d9e0f156fa2c2093ac0b6e68582b77c1b6f37036

test:
  secret_key_base: 8844699ab56ea33d8050e090300451ae2e8fb1092b50fdf2bbfc11e8e2f80f29f9a09be7de0c3068b314057bd92b3176c25f5148f12ae1222b294fa9c815bfc7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
